name: API Tests with RestAssured (Gradle)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Permite rodar manualmente pelo GitHub Actions

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Conceder permissão de execução ao Gradle Wrapper
        run: chmod +x gradlew

      - name: Baixar dependências e compilar o projeto
        run: ./gradlew build -x test

      - name: Rodar testes do RestAssured
        run: ./gradlew test
